In [2]:
import torch

seq_len = 4
mask = torch.tril(torch.ones(seq_len, seq_len))
print(mask)

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])


In [3]:
scores = torch.tensor([
    [2., 5., 8., 1.],
    [1., 4., 7., 3.],
    [3., 2., 6., 4.],
    [1., 5., 2., 8.]
])

scores = scores.masked_fill(mask==0, float('-inf'))

print(scores)

tensor([[2., -inf, -inf, -inf],
        [1., 4., -inf, -inf],
        [3., 2., 6., -inf],
        [1., 5., 2., 8.]])


In [4]:
import torch.nn.functional as F

attention = F.softmax(scores, dim=-1)

print(attention)

tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.7426e-02, 9.5257e-01, 0.0000e+00, 0.0000e+00],
        [4.6613e-02, 1.7148e-02, 9.3624e-01, 0.0000e+00],
        [8.6584e-04, 4.7273e-02, 2.3536e-03, 9.4951e-01]])
