# PyTorch Tensors

## 학습 내용
- 다양한 방법으로 Tensor 생성
- Tensor의 Shape, DataType, Device 확인
- CUDA(GPU)로 Tensor 이동
- Tensor 인덱싱 및 슬라이싱
- Tensor 결합 (torch.cat)
- 행렬곱 연산 (matmul, @)
- 원소별 연산 (mul)
- Tensor 집계 연산 (sum)
- In-place 연산 (_)
- Tensor <-> Numpy 배열 변환

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.type)

tensor([[1, 2],
        [3, 4]])
<built-in method type of Tensor object at 0x000001D8E3F65E50>


In [ ]:
# x_data와 같은 shape으로 1로 채운 tensor 생성
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

# x_data와 같은 shape으로 0 ~ 1 랜덤값 생성
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3795, 0.6540],
        [0.7071, 0.2379]]) 



In [4]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.9263, 0.3389, 0.8605],
        [0.7395, 0.2199, 0.2943]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [11]:
tensor = torch.rand(3, 4)

print(f"Shape or tensor: {tensor.shape}")
print(f"Datatype or tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape or tensor: torch.Size([3, 4])
Datatype or tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# CUDA로 이동
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [ ]:
tensor = torch.ones(4, 4)

print(f"First row: {tensor[0]}")
print(f"First Column: {tensor[:, 0]}")
# ...은 앞 차원 전부
print(f"Last Column: {tensor[..., -1]}")
# 두 번째 열 전부 0으로 변경
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# tensor 합치기
# dim = 0 세로 방향 1은 가로 방향 즉 [4, 12]
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [19]:
# tensor.T 는 전치. 행 열 변경
# @는 행렬곱 연산자
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
# 결과를 y3에 저장
torch.matmul(tensor, tensor.T, out=y3)

# 같은 위치 끼리 곱함
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
# tensor 값 전체 합
agg = tensor.sum()
# Pytorch tensor를 Python 숫자로 변환
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
print(f"{tensor} \n")
# in_place 연산
# _가 붙으면 원본 tensor를 직접 수정한다
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [28]:
# tensor를 numpy 배열로 변환
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
# numpy 배열을 tensor로 변환
# numpy 배열과 tensor는 같은 메모리를 공유할 수 있다.

# 복사가 아닌 같은 메모리 사용
n = np.ones(5)
t = torch.from_numpy(n)

# n의 모든 값에 1을 더하고 결과를 다시 n에 저장
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
